language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
    allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
