language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
    allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - composer test
  - composer check

after_success:
  - bash <(curl -s https://codecov.io/bash)
